### ISSUE TITLE
Binary Naming / Permissions

### ISSUE THREAD

**Issue by fabltd** [DVSwitch/IAX_Bridge#1]
Following the install guide I get to this:

Copy/rename the binary into the /opt/IAX_Bridge directory.

What should the file be called?  What perimssions does the file?

**Comment by MrBungle42** [comment]
Rename: Just remove the .platform (ie IAX_Bridge.AMD64 -> IAX_Bridge
Permissions: Execute

**Comment by fabltd** [comment]
Thanks can this be added to the doc?
